

name: Deploy App
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
#       - name: Checkout
#         uses: actions/checkout@v2



      - name: Setup key
        id: setup-key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
      - name: Update image on server
        run: |
             ssh -i $HOME/key.pem -o StrictHostKeyChecking=no ubuntu@34.217.101.197
             pwd
             ls -la /home/ubuntu/
